### ISSUE TITLE
Development : instructions in README fail

### ISSUE THREAD

**Issue by wayland** [maxGraph/maxgraph#261]
Hi all!

The following is what I'm seeing when I run the npm dev instructions contained in the README.  To reproduce:
1. Follow the instructions in the README ( https://github.com/maxGraph/maxGraph#setting-up-local-development-environment )
2. Mouse over any of the items in the left manu pane.
3. See errors

If it helps, I'm using Firefox 103.0.2.  

Thanks!

----- Errors -----
![image](https://github.com/maxGraph/maxGraph/assets/60692/28f0218d-d8f9-467a-b6a6-31bb3b506924)

```
plugin:vite:import-analysis] Failed to resolve entry for package "@maxgraph/core". The package may have incorrect main/module/exports specified in its package.json.

/home/wayland/src/UltimateSimpleSite/maxGraph/packages/html/stories/EdgeTolerance.stories.js

    at packageEntryFailure (file:///home/wayland/src/UltimateSimpleSite/maxGraph/packages/html/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28725:11)
    at resolvePackageEntry (file:///home/wayland/src/UltimateSimpleSite/maxGraph/packages/html/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28722:5)
    at tryNodeResolve (file:///home/wayland/src/UltimateSimpleSite/maxGraph/packages/html/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
    at Context.resolveId (file:///home/wayland/src/UltimateSimpleSite/maxGraph/packages/html/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28212:28)
    at async Object.resolveId (file:///home/wayland/src/UltimateSimpleSite/maxGraph/packages/html/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44276:32)
    at async TransformContext.resolve (file:///home/wayland/src/UltimateSimpleSite/maxGraph/packages/html/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:43992:23)
    at async normalizeUrl (file:///home/wayland/src/UltimateSimpleSite/maxGraph/packages/html/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41836:34)
    at async file:///home/wayland/src/UltimateSimpleSite/maxGraph/packages/html/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41998:47
    at async Promise.all (index 0)
    at async TransformContext.transform (file:///home/wayland/src/UltimateSimpleSite/maxGraph/packages/ht
```

**Comment by tbouffard** [comment]
Hi @wayland,
It seems that the `@maxgraph/core` package has not been built. 

It may not be very clear at the moment, but to run the Storybook examples (in the HTML folder), you must first build the "core" package or run it in "dev" mode.:
- In a first terminal, from the project root, run `npm run dev` and choose `@maxgraph/core`. Alternatively, from the packages/core folder, run `npm pack` (this builds the whole npm package)
- In a second terminal, from the project root, run `npm run dev` and choose `@maxgraph/html`

Please let me know if this helps.

**Comment by wayland** [comment]
Turns out `npm pack` was the missing piece.  PR submitted for README :) .
